region                  = "ap-south-1"
environment             = "prod"
vpc_cidr                = "10..1.0/16"
azs                     = ["ap-south-1a", "ap-south-1b"]
public_subnet_cidrs     = ["10.1.1.0/24", "10.1.2.0/24"]
private_subnet_cidrs    = ["10.1.11.0/24", "10.1.12.0/24"]
ecs_image               = "nginx:alpine"
rds_instance_class      = "db.t3.small"
rds_backup_retention    = 14
rds_deletion_protection = true
