region                  = "ap-south-1"
environment             = "dev"
vpc_cidr                = "10..0.0/16"
azs                     = ["ap-south-1a", "ap-south-1b"]
public_subnet_cidrs     = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs    = ["10.0.11.0/24", "10.0.12.0/24"]
ecs_image               = "nginx:alpine"
rds_instance_class      = "db.t3.micro"
rds_backup_retention    = 3
rds_deletion_protection = false
